IFC_CENTER='ifc_center'
METROGRAPH='metrograph'
ANGELIKA='angelika'
LINCOLN_CENTER='lincoln_center'
ANTHOLOGY_FILM_ARCHIVES='anthology_film_archives'

SOURCE_CHOICES = (IFC_CENTER, METROGRAPH, ANGELIKA, LINCOLN_CENTER, ANTHOLOGY_FILM_ARCHIVES)